[package]
name = "notifier"
version = "0.1.0"
authors = ["William <william@undefined.re>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zmq = "0.9.2"
failure = "0.1.6"
